// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_ggICi0InYKPmSVK2auHMr_gGjvnMw-8',
    appId: '1:27359947129:web:dd2ac1e27ead25123c27a8',
    messagingSenderId: '27359947129',
    projectId: 'moneytracker-65755',
    authDomain: 'moneytracker-65755.firebaseapp.com',
    storageBucket: 'moneytracker-65755.appspot.com',
    measurementId: 'G-GNNTF9V9BV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8li_SgyNPojACO10H1cX1r_x8xPek0FM',
    appId: '1:27359947129:android:ef74223226d022133c27a8',
    messagingSenderId: '27359947129',
    projectId: 'moneytracker-65755',
    storageBucket: 'moneytracker-65755.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDbVvfHZWxkOacAW5hWMdAWDP399YwxJA',
    appId: '1:27359947129:ios:0edabb4126e89f003c27a8',
    messagingSenderId: '27359947129',
    projectId: 'moneytracker-65755',
    storageBucket: 'moneytracker-65755.appspot.com',
    iosBundleId: 'com.example.expensetracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDbVvfHZWxkOacAW5hWMdAWDP399YwxJA',
    appId: '1:27359947129:ios:489fe19bb40392413c27a8',
    messagingSenderId: '27359947129',
    projectId: 'moneytracker-65755',
    storageBucket: 'moneytracker-65755.appspot.com',
    iosBundleId: 'com.example.expensetracker.RunnerTests',
  );
}
